name: GBA

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:      
    - name: Checkout repository and submodules
#TODO: uncomment when devkitarm will be updated to Debian Buster
#      uses: actions/checkout@v2
#      with:
#        submodules: recursive
      run: |
        git clone https://github.com/$GITHUB_REPOSITORY.git .
        git fetch origin $GITHUB_REF:temporary-ci-branch
        git checkout $GITHUB_SHA
        git submodule update --init --recursive
      
    - name: Make
      run: make -j$(nproc)
      
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: GBA ROM
        path: ./*.gba
