name: GBA

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Docker
      run: sudo apt-get install docker
      
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Pull DevKitARM Docker image
      run: docker pull devkitpro/devkitarm
      
    - name: Make
      run: docker run --rm -it -v "$PWD:/src" devkitpro/devkitarm make -C /src
      
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: GBA ROM
        path: \*.gba
